from collections import namedtuple


# Contains all information about a given sequence.
tSequenceReport = namedtuple('tSequenceReport', 
		['bPasses_filters', 
		'printready_output_string',
		'input_id',
		'input_seq',
		'output_id',
		'output_seq',
		'seq_is_reversed',
		'start_pos_forward_primer',
		'end_pos_forward_primer',
		'start_pos_ending_seq',
		'end_pos_ending_seq', 
		'errors_within_sequence'])


sFORWARD_PRIMER = 'CGCAATTCCTTTAGTTGTTC'
sREVERSE_PRIMER = 'AACCTCATACAGAAAATTCA'
sBEGINNING_FLANKING_SEQUENCE = 'CGACGGGGCT'
sENDING_FLANKING_SEQUENCE = 'GGGGCCGCTG'
# sFORWARD_PRIMER_COMPLEMENT = 'GAACAACTAAAGGAATTGCG' # generated dynamically
# sREVERSE_PRIMER_COMPLEMENT = 'TGAATTTTCTGTATGAGGTTTTGC' # generated dynamically
# sBEGINNING_FLANKING_SEQUENCE_COMPLEMENT = 'AGCCCCGTCG' # generated dynamically
# sENDING_FLANKING_SEQUENCE_COMPLEMENT = 'CAGCGGCCCC' # generated dynamically


dUnitTestSequences = {
'correct_normal_form_1': 'AGTCATCGCAATTCCTTTAGTTGTTCCTTTCTATTCTCACTCGGTCGACGGGGCTTGTACGGGGAAGAAGCCTTTGTTTTGTTGTGGGGCCGCTGGGGCCGAAACTGTTGAAAGTTGTTTAGCAAAACCTCATACAGAAAATTCA',
'correct_normal_form_2': 'ATGTCACGCAATTCCTTTAGTTGTTCCTTTCTATTCTCACTCGGCCGACGGGGCTTGTTCGTTTCTCGATCTTGCCGATTGTGGGGCCGCTGGGGCCGAAACTGTTGAAAGTTGTTTAGCAAAACCTCATACAGAAAATTCA',
'correct_reversed_complement_3': 'TGAATTTTCTGTATGAGGTTTTGCTAAACAACTTTCAACAGTTTCGGCCCCAGCGGCCCCACACTTCAGAGACATAGTCCGCTCACGACAAGCCCCGTCGGCCGAGTGAGAATAGAAAGGAACAACTAAAGGAATTGCGATGACT',
'correct_reversed_complement_4':'ACTATGAATTTTCTGTATGAGGTTTTGCTAAACAACTTTCAACAGTTTCGGCCCCAGCGGCCCCACACCTCCCCAGCATATCCGACCCACAAGCCCCGTCGGCCGAGTGAGAATAGAAAGGAACAACTAAAGGAATTGCGTAGT',
'forward_primer_has_random_char_inserted':'AGTCATCGCAATTCCTTTAZGTTGTTCCTTTCTATTCTCACTCGGTCGACGGGGCTTGTACGGGGAAGAAGCCTTTGTTTTGTTGTGGGGCCGCTGGGGCCGAAACTGTTGAAAGTTGTTTAGCAAAACCTCATACAGAAAATTCA',
'begins with nonexistent tissue tag':'ZZZZZAGTCATCGCAATTCCTTTAGTTGTTCCTTTCTATTCTCACTCGGTCGACGGGGCTTGTACGGGGAAGAAGCCTTTGTTTTGTTGTGGGGCCGCTGGGGCCGAAACTGTTGAAAGTTGTTTAGCAAAACCTCATACAGAAAATTCA',
'contains non-multiple-of-3 length of insert-sequence':'AGTCATCGCAATTCCTTTAGTTGTTCCTTTCTATTCTCACTCGGTCGACGGGGCTTGTACGGGGZZAAGAAGCCTTTGTTTTGTTGTGGGGCCGCTGGGGCCGAAACTGTTGAAAGTTGTTTAGCAAAACCTCATACAGAAAATTCA',
'contains incorrect beginning flanking sequence':'AGTCATCGCAATTCCTTTAGTTGTTCCTTTCTATTCTCACTCGGTCGZZZZZACGGGGCTTGTACGGGGAAGAAGCCTTTGTTTTGTTGTGGGGCCGCTGGGGCCGAAACTGTTGAAAGTTGTTTAGCAAAACCTCATACAGAAAATTCA'
}

dUnitTestCorrectTags = ['AGTCAT', 'ATGTCA', ]

#def ParseTissueTagsFile():
#	pass

#dTissueTagsDictionary = ParseTissueTagsFile()
